# Generated by Django 4.2.11 on 2024-04-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_about_about_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='calendar',
            new_name='calendar_photo',
        ),
    ]
