# Generated by Django 4.2.11 on 2024-04-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_calendar_calendar_calendar_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='calendar_photo',
            new_name='calendar',
        ),
    ]
