# Generated by Django 4.2.11 on 2024-04-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_calendar_photo_calendar_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buletins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='uploads/buletins')),
            ],
            options={
                'verbose_name_plural': 'Buletins',
            },
        ),
    ]
