# Generated by Django 4.2.11 on 2024-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_buletins'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
