# Generated by Django 4.2.11 on 2024-04-10 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_popupmessage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='buletins',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 10, 2, 30, 58, 98378, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
